---
title: "WUP_Linear"
author: "Anjolie Barrios"
date: "fall 2020"
output: 
  html_document:
    number_sections: true
    toc: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(tidyverse)
require(tidyverse)
require(knitr)
linear <- read.csv(file="http://onlinestatbook.com/case_studies_rvls/physical_strength/data.txt",sep="",header=TRUE)
if(!require("rglwidget")) {install.packages("rglwidget");require("rglwidget")}
```

# Displays
>Scatterplots of data with fits 

```{r}
model.1 <- lm(SIMS ~ ARM, data = linear)
data1 <- ggplot(linear,aes(y=SIMS,x=ARM))
data1 + geom_point() + geom_smooth(method = lm)
  
model.2 <- lm(SIMS ~ GRIP, data = linear)
data2 <- ggplot(linear,aes(y=SIMS,x=GRIP))
data2 + geom_point() + geom_smooth(method = lm)
  
model.3 <- lm(SIMS ~ ARM+GRIP, data = linear)
data3 <- ggplot(linear,aes(y=SIMS,x=ARM+GRIP))
data3 + geom_point() + geom_smooth(method = lm)
```

# Model results 
>with comments on model fit metrics

```{r}
summary.lm(model.1)
summary.lm(model.2)
summary.lm(model.3)
```

# Model comparison  
>model1 vs model3, with anova. 
